// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package container

import (
	"database/sql"
	"github.com/google/wire"
	"github.com/kianooshaz/skeleton/foundation/config"
	"github.com/kianooshaz/skeleton/foundation/database/postgres"
	"github.com/kianooshaz/skeleton/foundation/log"
	"github.com/kianooshaz/skeleton/internal/app/web/protocol"
	"github.com/kianooshaz/skeleton/internal/app/web/rest"
	"github.com/kianooshaz/skeleton/services/account/username/proto"
	"github.com/kianooshaz/skeleton/services/account/username/service"
	"github.com/kianooshaz/skeleton/services/authentication/password/proto"
	"github.com/kianooshaz/skeleton/services/authentication/password/service"
	"github.com/kianooshaz/skeleton/services/organization/organization/proto"
	"github.com/kianooshaz/skeleton/services/organization/organization/service"
	"github.com/kianooshaz/skeleton/services/risk/audit/proto"
	"github.com/kianooshaz/skeleton/services/risk/audit/service"
	"github.com/kianooshaz/skeleton/services/user/user/proto"
	"github.com/kianooshaz/skeleton/services/user/user/service"
	"log/slog"
	"os"
)

// Injectors from web_wire.go:

// NewWebContainer creates a new web dependency injection container.
func NewWebContainer() (*WebContainer, error) {
	appConfig, err := ProvideAppConfig()
	if err != nil {
		return nil, err
	}
	db, err := ProvideDatabase(appConfig)
	if err != nil {
		return nil, err
	}
	logger := ProvideLogger(appConfig)
	baseContainer := ProvideBaseContainer(appConfig, db, logger)
	webService, err := ProvideRestServer(appConfig, logger)
	if err != nil {
		return nil, err
	}
	userService := ProvideUserService(appConfig, db, logger)
	organizationService := ProvideOrgService(appConfig, db, logger)
	usernameService := ProvideUsernameService(appConfig, db, logger)
	auditService := ProvideAuditService(appConfig, db, logger)
	passwordService := ProvidePasswordService(appConfig, db, logger)
	webContainer := &WebContainer{
		BaseContainer:   baseContainer,
		RestServer:      webService,
		UserService:     userService,
		OrgService:      organizationService,
		UsernameService: usernameService,
		AuditService:    auditService,
		PasswordService: passwordService,
	}
	return webContainer, nil
}

// web_wire.go:

// ProvideAppConfig loads the application configuration using dependency injection.
func ProvideAppConfig() (*AppConfig, error) {
	configPath := "config.yml"
	if envPath := os.Getenv("CONFIG_PATH"); envPath != "" {
		configPath = envPath
	}

	cfg, err := config.LoadWithFile[AppConfig](configPath, "app")
	if err != nil {
		return nil, err
	}
	return &cfg, nil
}

// ProvideLogger creates a structured logger using dependency injection.
func ProvideLogger(cfg *AppConfig) *slog.Logger {
	return log.NewLogger(cfg.Logger)
}

// ProvideDatabase creates a database connection.
func ProvideDatabase(cfg *AppConfig) (*sql.DB, error) {
	return postgres.NewConnection(cfg.Database)
}

// ProvideBaseContainer creates a base container with common dependencies.
func ProvideBaseContainer(cfg *AppConfig, db *sql.DB, logger *slog.Logger) *BaseContainer {
	return &BaseContainer{
		Config: cfg,
		DB:     db,
		Logger: logger,
	}
}

// ProvideRestServer creates a REST server instance.
func ProvideRestServer(cfg *AppConfig, logger *slog.Logger) (protocol.WebService, error) {
	return rest.New(cfg.RestServer, logger)
}

// ProvideUserService creates a user service instance.
func ProvideUserService(cfg *AppConfig, db *sql.DB, logger *slog.Logger) userproto.UserService {
	return uus.New(db, logger)
}

// ProvideOrgService creates an organization service instance.
func ProvideOrgService(cfg *AppConfig, db *sql.DB, logger *slog.Logger) orgproto.OrganizationService {
	return oos.New(db, logger)
}

// ProvideUsernameService creates a username service instance.
func ProvideUsernameService(cfg *AppConfig, db *sql.DB, logger *slog.Logger) usernameproto.UsernameService {
	return auns.New(cfg.Account.Username, db, logger)
}

// ProvideAuditService creates an audit service instance.
func ProvideAuditService(cfg *AppConfig, db *sql.DB, logger *slog.Logger) auditproto.AuditService {
	return service.New(cfg.Risk.Audit, db, logger)
}

// ProvidePasswordService creates a password service instance.
func ProvidePasswordService(cfg *AppConfig, db *sql.DB, logger *slog.Logger) passwordproto.PasswordService {
	return authpass.New(cfg.Authentication.Password, db, logger)
}

// BaseProviderSet contains providers for base container dependencies.
var BaseProviderSet = wire.NewSet(
	ProvideAppConfig,
	ProvideLogger,
	ProvideDatabase,
	ProvideBaseContainer,
)

// WebProviderSet contains providers for web container dependencies.
var WebProviderSet = wire.NewSet(
	BaseProviderSet,
	ProvideRestServer,
	ProvideUserService,
	ProvideOrgService,
	ProvideUsernameService,
	ProvideAuditService,
	ProvidePasswordService,
)
