app:
  web:
    shutdown_timeout: "30s"

postgres:
  name: "postgres"
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "password"
  sslmode: "disable"

rest_server:
  debug: true
  address: ":8080"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "30s"
  body_limit_size: "2M"
  cors:
    allowed_origins: ['*']
    allowed_headers: []
    allowed_methods: ['GET', 'HEAD', 'PUT', 'POST', 'PATCH', 'DELETE']
    allow_credentials: false
    exposed_headers: []
    max_age: 0
  rate_limit:
    enable: false
    rate: 10
    burst: 100
    duration: "1m"
