version: 0.0.0
shutdown_timeout: 30s
rest:
  debug: true
  address: 0.0.0.0:8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 30s
  cors:
    allowed_origins: ['*']
    allowed_headers: []
    allowed_methods: ['GET', 'HEAD', 'PUT', 'POST', 'PATCH', 'DELETE']
    allow_credentials: false
    exposed_headers: []
    max_age: 0
  body_limit_size: '1KB'
  rate_limit:
    rate: 2
    burst: 30
    duration: 1h